#include <stdio.h>
#include "lib/code_status.h"
#include "lib/dequeue.h"
#include "lib/patient.h"

int
main() {
    Patient p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12;
    Dequeue* dequeue = NULL;
    init_patient(&p1);
    init_patient(&p2);
    init_patient(&p3);
    init_patient(&p4);
    init_patient(&p5);
    init_patient(&p6);
    init_patient(&p7);
    init_patient(&p8);
    init_patient(&p9);
    init_patient(&p10);
    init_patient(&p11);
    init_patient(&p12);
    init_dequeu(&dequeue, 15);
    fill_patient(&p1, "a", 0, 0, 0);
    fill_patient(&p2, "b", 0, 0, 0);
    fill_patient(&p3, "c", 0, 0, 0);
    fill_patient(&p4, "d", 0, 0, 0);
    fill_patient(&p5, "e", 0, 0, 0);
    fill_patient(&p6, "f", 0, 0, 0);
    fill_patient(&p7, "g", 0, 0, 0);
    fill_patient(&p8, "h", 0, 0, 0);
    fill_patient(&p9, "j", 0, 0, 0);
    fill_patient(&p10, "k", 0, 0, 0);
    fill_patient(&p11, "l", 0, 0, 0);
    fill_patient(&p12, "m", 0, 0, 0);
    push_front(dequeue, &p1);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p2);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p3);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p4);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p5);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p6);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p7);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p8);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p9);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p10);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p11);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    push_front(dequeue, &p12);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    pop_front(dequeue);
    printf("%d ", get_cnt(dequeue));
    print_dequeue(dequeue);
    dealloc_dequeue(dequeue);
    return 0;
}
